# Generated by Django 5.1.6 on 2025-06-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_image_product_image_remove_product_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='SellerID',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
