# Generated by Django 5.1.6 on 2025-08-05 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_product_image'),
        ('loginreg', '0003_seller_sellerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='images/product_images/'),
        ),
        migrations.CreateModel(
            name='StoreAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StoreName', models.CharField(blank=True, max_length=200, null=True)),
                ('Address', models.TextField(blank=True, null=True)),
                ('City', models.CharField(blank=True, max_length=100, null=True)),
                ('State', models.CharField(blank=True, max_length=100, null=True)),
                ('ZipCode', models.CharField(blank=True, max_length=10, null=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loginreg.seller')),
            ],
        ),
    ]
