# Generated by Django 5.1.6 on 2025-03-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(blank=True, max_length=120, null=True)),
                ('LastName', models.CharField(blank=True, max_length=120, null=True)),
                ('Email', models.EmailField(max_length=120, unique=True)),
                ('PhoneNumber', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('Gender', models.CharField(blank=True, max_length=120)),
                ('Password', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
