# Generated by Django 5.1.7 on 2025-07-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(blank=True, max_length=120, null=True)),
                ('LastName', models.CharField(blank=True, max_length=120, null=True)),
                ('Email', models.EmailField(max_length=120, unique=True)),
                ('PhoneNumber', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('Gender', models.CharField(blank=True, max_length=120)),
                ('Password', models.CharField(blank=True, max_length=200, null=True)),
                ('UserType', models.CharField(default='S', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='UserType',
            field=models.CharField(default='C', max_length=1),
        ),
    ]
