# Generated by Django 5.1.6 on 2025-08-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg', '0002_seller_users_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='SellerID',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
