# Generated by Django 5.1.6 on 2025-08-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg', '0003_seller_sellerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile_pics/'),
        ),
        migrations.AddField(
            model_name='users',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile_pics/'),
        ),
    ]
